### ISSUE TITLE
Oculus Port?

### ISSUE THREAD

**Issue by getbiks** [caffeine239/BeatSaberClone#1]
Hi, Is there any way i can port it to oculus?

**Comment by jordimeije** [comment]
Can you try to use steamVR with oculus?

**Comment by caffeine239** [comment]
i will try for oculus next, i will need testers tho.

**Comment by caffeine239** [comment]
Pending fix for Oculus, waiting on a tester.

**Comment by getbiks** [comment]
Hi, I will test tomorrow and let you know about the oculus. Thanks :)

**Comment by caffeine239** [comment]
confirmed working on Rift.

**Comment by caffeine239** [comment]
and WMR
